# Generated by Django 5.2.1 on 2025-10-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_pic',
            new_name='profile_pic',
        ),
    ]
